job:
  name: test-v5
  env_type: docker
  loop: False

tpu:
  allocation_mode: "queued-resources"    # tpu-vm | queued-resources
  accelerator: v5litepod-16
  name: yufeng-${tpu.accelerator}
  zone: europe-west4-b
  version: v2-alpha-tpuv5-lite
  pricing: spot                   
  # spot | ondemand | preemptible
  startup_script: null
  tags: ["jobman", "experiment"]
  metadata:
    owner: "yufeng"
    # owner can be used to map tpus to user I think
    purpose: "testing jobman"

gcsfuse:
  bucket_name: llm_pruning_europe_west4
  mount_path: /home/zephyr/gcs-bucket

ssh:
  private_key: ~/.ssh/id_rsa
  identities:
    - private_key: ~/.ssh/id_rsa
      public_key: ~/.ssh/id_rsa.pub
      config_entry: | 
        Host 10.*
          IdentityFile ~/.ssh/id_rsa
          IdentitiesOnly yes
    - private_key: ~/.ssh/id_ed25519_github
      public_key: ~/.ssh/id_ed25519_github.pub
      config_entry: |
        Host github.com
          User git
          IdentityFile ~/.ssh/id_ed25519_github
          IdentitiesOnly yes

docker:
  image: yx3038/maxtext_base_image:latest
  mount_dirs:
    - /home/zephyr
    - /dev
    - /run
    - /home/zephyr/.config/gcloud:/root/.config/gcloud
    - /home/zephyr/.ssh:/root/.ssh
  workdir: /home/zephyr
  flags: ["--privileged", "--network=host"]

conda:
  name: fms
  config_file: assets/fms.yaml

venv:
  name: maxtext
  requirements_file: assets/requirements.txt  
  python: "3.9"  

command:
  cmd: |
    pip show jax
    pip show flax
  workers: [0] # int | list | "all"