job:
  name: test-v6
  env_type: docker
  loop: False

tpu:
  allocation_mode: "queued-resources"    # tpu-vm | queued-resources
  accelerator: v6e-4
  name: yufeng-${tpu.accelerator}
  zone: us-east1-d
  version: v2-alpha-tpuv6e
  pricing: spot                   
  # spot | ondemand | preemptible
  startup_script: null
  tags: ["jobman", "experiment"]
  metadata:
    owner: "yufeng"
    # owner can be used to map tpus to user I think
    purpose: "testing jobman"

gcsfuse:
  bucket_name: llm_pruning_us_east1_d
  mount_path: /home/zephyr/gcs-bucket

ssh:
  private_key: ~/.ssh/id_rsa
  identities:
    - private_key: ~/.ssh/id_rsa
      public_key: ~/.ssh/id_rsa.pub
      config_entry: | 
        Host 10.*
          IdentityFile ~/.ssh/id_rsa
          IdentitiesOnly yes
    - private_key: ~/.ssh/id_ed25519_github
      public_key: ~/.ssh/id_ed25519_github.pub
      config_entry: |
        Host github.com
          User git
          IdentityFile ~/.ssh/id_ed25519_github
          IdentitiesOnly yes

docker:
  image: yx3038/maxtext_base_image:latest
  env_vars:
    - HOME=/home/zephyr
  mount_dirs:
    - /home/zephyr
    - /dev
    - /run
    - /home/zephyr/.config/gcloud:/root/.config/gcloud
    # - /home/zephyr/.ssh:/root/.ssh
  workdir: /home/zephyr
  flags: ["--privileged", "--network=host"]

conda:
  name: fms
  config_file: assets/fms.yaml

venv:
  name: maxtext
  requirements_file: assets/requirements.txt  
  python: "3.9"  

command:
  cmd: |
    # pip show jax
    # pip show flax

    # rm -rf /home/zephyr/maxtext
    # cp -r /home/zephyr/gcs-bucket/maxtext /home/zephyr/maxtext
    # mkdir -p /home/zephyr/maxtext/logs

    # gcloud config set project vision-mix
    # gcloud config set compute/zone ${tpu.zone}
    # export TPU_PREFIX=${tpu.name}
    # export BUCKET_NAME=${gcsfuse.bucket_name}
    # cd /home/zephyr/maxtext
    # bash scripts/llama3.1_4b_width_S50.sh

    # pip install torch
    # cd /home/zephyr/gcs-bucket/maxtext
    # bash tests/test_eq.sh    
    
  workers: [0] # int | list | "all"